import type { GameId, SkillId } from "../types";

export interface GameDef {
  id: GameId;
  title: string;
  childTitle: string;
  primarySkill: SkillId | null;
  secondarySkills: SkillId[];
  minAge: number;
  maxAge: number;
  scored: boolean;
  mechanic: string;
  tutorial: string;
  success: string;
  retry: string;
}

export const GAMES: Record<Exclude<GameId, never>, GameDef> = {
  warmup: {
    id: "warmup",
    title: "Primeros pasos",
    childTitle: "Hola",
    primarySkill: null,
    secondarySkills: [],
    minAge: 4,
    maxAge: 8,
    scored: false,
    mechanic: "tap + drag",
    tutorial: "La mascota demuestra tocar y arrastrar.",
    success: "¡Ya sabemos jugar!",
    retry: "Mira cómo lo hago.",
  },
  semaforo: {
    id: "semaforo",
    title: "Semáforo Mágico",
    childTitle: "Estrellas",
    primarySkill: "attention_inhibition",
    secondarySkills: [],
    minAge: 4,
    maxAge: 8,
    scored: true,
    mechanic: "go / no-go",
    tutorial: "Toca la estrella solo si el cristal está verde.",
    success: "Esperaste el momento justo.",
    retry: "Espera al cristal verde.",
  },
  luciernagas: {
    id: "luciernagas",
    title: "Camino de Luciérnagas",
    childTitle: "Luciérnagas",
    primarySkill: "visual_memory",
    secondarySkills: ["visuospatial"],
    minAge: 4,
    maxAge: 8,
    scored: true,
    mechanic: "sequence recall",
    tutorial: "Las luces se encienden. Tú las sigues.",
    success: "Recordaste el camino.",
    retry: "Mira el camino otra vez.",
  },
  camaleon: {
    id: "camaleon",
    title: "Camaleón Clasificador",
    childTitle: "Colores",
    primarySkill: "flexibility",
    secondarySkills: ["reasoning"],
    minAge: 4,
    maxAge: 8,
    scored: true,
    mechanic: "rule switch",
    tutorial: "Primero por color. Luego por forma.",
    success: "Cambiaste de regla.",
    retry: "Ahora la regla es otra.",
  },
  historia: {
    id: "historia",
    title: "La Historia Perdida",
    childTitle: "Cuento",
    primarySkill: "visual_memory",
    secondarySkills: ["language"],
    minAge: 5,
    maxAge: 8,
    scored: true,
    mechanic: "narrative sequence",
    tutorial: "Mira el cuento. Luego ordénalo.",
    success: "El cuento volvió a su sitio.",
    retry: "¿Qué pasó primero?",
  },
  quesigue: {
    id: "quesigue",
    title: "¿Qué sigue?",
    childTitle: "Patrones",
    primarySkill: "reasoning",
    secondarySkills: [],
    minAge: 5,
    maxAge: 8,
    scored: true,
    mechanic: "pattern completion",
    tutorial: "Mira lo que se repite y elige la pieza.",
    success: "El patrón encajó.",
    retry: "Mira otra vez la fila.",
  },
  casa: {
    id: "casa",
    title: "Casa Puzzle",
    childTitle: "Casa",
    primarySkill: "visuospatial",
    secondarySkills: ["reasoning"],
    minAge: 4,
    maxAge: 8,
    scored: true,
    mechanic: "construction",
    tutorial: "Pon cada pieza en su lugar.",
    success: "La casa está lista.",
    retry: "Prueba otra pieza.",
  },
  bosque: {
    id: "bosque",
    title: "Bosque de Palabras",
    childTitle: "Palabras",
    primarySkill: "language",
    secondarySkills: [],
    minAge: 4,
    maxAge: 8,
    scored: true,
    mechanic: "receptive vocabulary",
    tutorial: "Escucha y toca la imagen.",
    success: "Esa era la palabra.",
    retry: "Escucha otra vez.",
  },
  mercado: {
    id: "mercado",
    title: "Mercado Mágico",
    childTitle: "Mercado",
    primarySkill: "numeracy",
    secondarySkills: [],
    minAge: 4,
    maxAge: 8,
    scored: true,
    mechanic: "quantity",
    tutorial: "Toca la cantidad que te piden.",
    success: "¡Justo esas!",
    retry: "Contemos despacio.",
  },
  guardianes: {
    id: "guardianes",
    title: "Guardianes del Bosque",
    childTitle: "Amigo",
    primarySkill: "attention_inhibition",
    secondarySkills: [],
    minAge: 4,
    maxAge: 8,
    scored: true,
    mechanic: "visual search",
    tutorial: "Toca al amigo con la hojita. Los demás se quedan.",
    success: "Lo encontraste.",
    retry: "Busca la hojita.",
  },
};

export const PLAYABLE_GAMES: GameId[] = [
  "semaforo",
  "luciernagas",
  "camaleon",
  "historia",
  "quesigue",
  "casa",
  "bosque",
  "mercado",
  "guardianes",
];
